config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'foods#index'
  resources :foods, only: [:index, :create, :new, :destroy]

  resources :recipes, only: [:index, :show, :create, :new, :destroy] do
    resources :recipe_foods, only: [:new, :destroy]
  end
  
  resources :recipe_foods, only: [:index, :edit, :update, :destroy, :create, :new]

  resources :public_recipes, only: %i[index]

  devise_scope :user do 
    authenticated :user do 
      root 'users#index', as: :authenticated_root 
    end
    unauthenticated do 
      root 'devise/sessions#new', as: :unauthenticated_root 
    end 
  end

  get 'shopping_list', to: 'shopping_list#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.role == 'admin'
      can :manage, :all
    else
      can :read, Recipe do |recipe|
        recipe.user == user || recipe.public
      end
    end

    can [:update, :destroy], Recipe do |recipe|
      recipe.user == user
    end

    can :read, Food
    can :destroy, Food do |food|
      food.user.id == user.id
    end
    can %i[create], :all

    # return unless user.present?

    # can :read, Recipe, public: true
    # can :manage, Recipe, user: user
    # can :manage, Food, user: user
    # can :manage, Inventory, user: user
    # can :read, Food
    # can :create, :all
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :inventory_foods, dependent: :destroy

  validates :name, :measurement_unit, :price, presence: true
  validates :price, numericality: { greater_than: 0 }
end

app/models/inventory.rb
class Inventory < ApplicationRecord
end

app/models/inventory_food.rb
class InventoryFood < ApplicationRecord
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy

  validates :name, presence: true
  validates :description, presence: true, length: { maximum: 250 }
  validates :cooking_time, :preparation_time, numericality: { greater_than_or_equal_to: 0 }
  validates :public, inclusion: { in: [true, false] }

  def total_items
    recipe_foods.sum(:quantity)
  end

  def total_price
    recipe_foods.joins(:recipe, :food).sum('price * quantity')
  end
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  validates :food_id, presence: true, uniqueness: { scope: :recipe_id }
  validates :quantity, presence: true, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  after_create :set_role
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :foods, dependent: :destroy
  has_many :recipes, dependent: :destroy
  validates :name, presence: true

  def set_role
    update(role: 'user')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :surname, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :surname, :email, :password, :current_password)
    end
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  load_and_authorize_resource
  before_action :set_food, only: %i[show destroy]

  def index
    if user_signed_in?
      @food = current_user.foods
    else
      redirect_to user_session_path
    end
  end

  def new
    @food = Food.new
  end

  def create
    @food = current_user.foods.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to foods_url, notice: 'Food was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @recipes = RecipeFood.where(food_id: @food.id)
    @recipes.each(&:delete)
    @food.delete
    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
    end
  end

  private

  def set_food
    @food = Food.find(params[:id])
  end

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price)
  end
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :set_recipe_food, only: %i[edit update destroy]
  before_action :set_foods, only: %i[edit new update]

  def new
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = @recipe.recipe_foods.new
    @recipe_food.save
  end

  def create
    @recipe_food = RecipeFood.new(recipe_food_params)

    respond_to do |format|
      if @recipe_food.save
        format.html do
          redirect_to recipe_path(@recipe_food.recipe), notice: 'Recipe food was successfully created.'
        end
      else
        set_foods
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @recipe_food.update(recipe_food_params)
        format.html do
          redirect_to recipe_path(recipe_food_params[:recipe_id]), notice: 'Recipe food was successfully updated.'
        end
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @recipe_food = RecipeFood.find(params[:id])
    @recipe_food.destroy
    flash[:success] = 'Recipe Food deleted successfully.'
    redirect_to recipe_path(@recipe_food.recipe_id)
  end

  private

  def set_foods
    @foods = current_user.foods.map { |food| [food.name, food.id] }
  end

  def set_recipe_food
    @recipe_food = RecipeFood.includes(:recipe, :food).find(params[:id])
  end

  def recipe_food_params
    params.fetch(:recipe_food, {}).permit(:quantity, :food_id, :recipe_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  load_and_authorize_resource
  def index
    @recipes = Recipe.where(user_id: current_user.id)
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = current_user.recipes.build(recipe_params)

    respond_to do |format|
      format.html do
        if @recipe.save
          redirect_to recipes_url, notice: 'Recipe created successfully'
        else
          render :new, alert: 'Recipe not created. Please try again!'
        end
      end
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    flash[:notice] = 'The recipe was successfully destroyed.'
    redirect_to recipes_url
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :description, :public, :preparation_time, :cooking_time)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/helpers/inventory_foods_helper.rb
module InventoryFoodsHelper
end

app/helpers/public_recipes_helper.rb
module PublicRecipesHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/shopping_list_helper.rb
module ShoppingListHelper
  def foods_join
    # rubocop:disable Lint/UselessAssignment
    foods_join = Food.joins(:recipe_foods).where(user_id: current_user.id)
    # rubocop:enable Lint/UselessAssignment
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/_form.html.erb
<div class="container food-form">

<%= form_with(model: food) do |form| %>
  <div class="card form">
  <div class="card-body">
  <div class="mb-3">
    <%= form.label :name, class: "form-label" %>
    <div>
      <%= form.text_field :name, autofocus: true, class: "form-control", required: true %>
    </div>
  </div>

  <div>
    <%= form.label :measurement_unit, class: "form-label" %>
    <div>
      <%= form.text_field :measurement_unit, autofocus: true, class: "form-control", required: true %>
    </div>
  </div>

  <div>
    <%= form.label :price, class: "form-label" %>
    <div>
      <%= form.number_field :price, autofocus: true, class: "form-control", required: true, min: 1 %>
    </div>
  </div>

  <div>
    <%= form.submit class: "btn btn-primary btn-floating mx-1 food-btn" %>
  </div>
</div>
</div>
<% end %> 

app/views/foods/index.html.erb
<div class="container">
  <%= link_to 'Add Food', new_food_path, class: "btn btn-primary btn-floating mx-1 add-btn"%>


<div>
  <table class="table border">
    <thead class="bg-dark text-white">
      <tr>
        <th scope="col">Food</th>
        <th scope="col" title="measurement">Measurement unit</th>
        <th scope="col" title="price">Unit price</th>
        <th>Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @foods.each do |food| %>
        <tr>
          <th scope="row"><%= food.name %></th>
          <td><%= food.measurement_unit %></td>
          <td>$<%= food.price %></td>
          <td><%= button_to 'Delete', food_url(food), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link delete-btn" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
</div>

app/views/foods/new.html.erb
<div  class="container">
  <div class="text-center">
		<h1>Add new food</h1>
	</div>

		
		<%= render 'form', food: @food %>
		<div class="text-center">
		<%= link_to 'Back', url_for(:back) %>
		</div>
	</div>
</div>

app/views/inventories/index.html.erb
<h1>Inventories#index</h1>
<p>Find me in app/views/inventories/index.html.erb</p>

app/views/inventories/show.html.erb
<h1>Inventories#show</h1>
<p>Find me in app/views/inventories/show.html.erb</p>

app/views/recipe_foods/_form.html.erb
<%= form_with(model: recipe_food) do |form| %>
  <div class="field container">
    <%= form.label :food, class: "label" %>
    <div class="select is-fullwidth">
      <%= form.select :food_id, @foods %>
    </div>
  </div>

  <div class="field container">
    <%= form.label :quantity, class: "form-label" %>
    <div class="control">
      <%= form.text_field :quantity, class: "form-control", type: "number", required: true, min: 1 %>
    </div>
  </div>

  <%= form.hidden_field :recipe_id, value: recipe_food.recipe_id %>

  <div class="actions container p-3">
    <%= form.submit class: "btn btn-primary d-flex m-auto" %>
  </div>
<% end %>

app/views/recipe_foods/_index.html.erb
<% if @recipe.recipe_foods %>
<div class="table-container">
  <table class="table border">
    <thead class="bg-dark text-white">
      <tr>
        <th>Food</th>
        <th>Quantity</th>
        <th>Value</th>
        <th>Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @recipe.recipe_foods.each do |recipe_food| %>
        <tr>
          <th><%= recipe_food.food.name %></th>
          <td><%= pluralize(recipe_food.quantity, recipe_food.food.measurement_unit) %></td>
          <td>$<%= recipe_food.quantity * recipe_food.food.price %></td>
			    <% if can? :update, recipe_food.recipe %>
            <td>
              <div class="buttons d-flex">
                <%= link_to 'Edit', edit_recipe_food_path(recipe_food), class: "btn btn-link is-small is-success is-light actions-btn"  %>
                <%= button_to "Delete", recipe_recipe_food_path(@recipe, recipe_food), method: :delete, class: "btn btn-link is-small is-success is-light actions-btn"%>
              </div>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
</div>
<% end %>

app/views/recipe_foods/edit.html.erb
<div class="container w-50">
  <div class="column is-two-fifths-desktop">
		<h3 class="title is-4 text-center pb-3">Edit Ingredient</h3>
		<div class="card">
		<div class="card-body">
		<%= render 'form', recipe_food: @recipe_food %>
		<div class="d-flex m-auto">
		<%= link_to 'Back', url_for(:back), class: "button is-light d-flex m-auto" %>
		</div>
		</div>
			</div>
	</div>
</div>

app/views/recipe_foods/new.html.erb
<div class="container w-50 text-center">

<%= form_with(model: @recipe_food) do |form| %>
  <div class="card form">
  <div class="card-body">
  <div class="field container">
    <%= form.label :food, class: "form-label p-2" %>
    <div class="select">
      <%= form.select :food_id, @foods, class: "form-select"  %>
    </div>
  </div>

  <div class="field container">
    <%= form.label :quantity, class: "form-label p-2" %>
    <div class="control">
      <%= form.text_field :quantity, class: "form-control", type: "number", required: true, min: 1 %>
    </div>
  </div>

  <%= form.hidden_field :recipe_id, value: @recipe_food.recipe_id %>

  <div class="actions rf-btn p-3">
    <%= form.submit class: "btn btn-primary btn-floating mx-1" %>
  </div>
</div>
</div>
<% end %>

</div>

app/views/recipes/_recipe.html.erb
<div class="fs-4 p-3 border border-1 container mt-5 p-2 bio">
  <%= form_with model: @recipe, method: :post, local: true do |f| %>
    <%= f.label :name, "Name", class: "form-label fs-6" %><br>
    <%= f.text_field :name, :placeholder => "Add Your Recipe name here...", required: true, class: "form-control" %><br>

    <%= f.label :description, "Write description", class: "form-label fs-6" %>
    <%= f.text_area :description, size: "80x15", :placeholder => "Add your description here...", required: true, class: "form-control" %>
    <%= f.label :cooking_time, "Cooking time(mins)", class: "form-label fs-6" %>
    <%= f.text_field :cooking_time, class: "form-control mb-2" %>
    <%= f.label :preparation_time, "Preparation time(mins)", class: "form-label fs-6" %>
    <%= f.text_field :preparation_time, class: "form-control mb-2" %>

    <div class="text-center">
    <%= f.label :public, "Make it Public?", class: "form-label fs-6" %>
    <%= f.check_box :public, class: "mb-2" %>
    </div>
    <%= f.submit "Add Recipe", data: {disable_with: "Adding..."}, class: "btn btn-primary btn-floating mx-1 w-100" %>
  <% end %>
</div>  

app/views/recipes/index.html.erb
<div class="is-flex is-justify-content-end my-6 container">
  <%= link_to 'Create Recipe', new_recipe_path, class: "btn btn-dark cr-btn" %>
</div>
<div>
  <ul>
    <% if @recipes.size > 0%>
    <% @recipes.each do |r| %>
    <li class="border border-2 border-primary container mt-5 rounded bio">
      <div class="d-flex p-3">
        <div class="r-name">
          <%= link_to recipe_path(r.id), id: "recipe_path#{r.id}" do %>
          <h4 class="text-dark"><%= r.name%></h4>
          <% end %>
          <div>
            <%= button_to "Remove", recipe_path(r.id), method: :delete, class: "btn btn-primary btn-floating mx-1 d-btn"%>
          </div>
        </div>
        <div>
          <p><%= r.description%></p>
        </div>
      </div>
    </li>
    <% end %>
    <% else %>
    <p class="border border-2 container mt-5 p-2 bio px-5 fs-1">There are no recipes registered!</p>
    <% end %>
  </ul>
</div>

app/views/recipes/new.html.erb
<h3 class="text-center" > Create Your Recipe</h3>
<div class="recipe-form">
  <%= render "recipe" %>
</div> 

app/views/recipes/show.html.erb
<div class="border border-2 border-primary container p-2 my-5 rounded recipe">
  <div class="my-3 text-center">
    <h2 class><%= @recipe.name%></h2>
  </div>
  <div>
    <div class="split">
      <div class="d-flex justify-content-between p-2">
        <h5> Preparation time: <%= @recipe.preparation_time %> min </h5>
        <div class="public-btn">
        <% if @recipe.public %>
          Public: <input type="checkbox" checked="true" class="mx-4" >
        <% end %>
        <% if !@recipe.public %>
          Public: <input type="checkbox" class="mx-4" >
        <% end %>
      </div>
      </div>
    </div>
    <div>
      <h5 class="p-2"> Cooking time: <%= @recipe.preparation_time %> min </h5>
      <h5 class="p-2"> Steps go here...</h5>
    </div>
    <div class="d-flex justify-content-around p-3">
    <%= link_to 'Generate shopping list', shopping_list_path, class: "btn btn-primary btn-floating mx-1 r-btn" %>
			<% if can? :update, @recipe %>
				<%= link_to 'Add ingredient', new_recipe_recipe_food_path(@recipe), class: "btn btn-primary btn-floating mx-1 r-btn" %>
			<% end %>
    </div>
    <div class="column is-three-quarters">
		<%= render partial: "recipe_foods/index", locals: { recipe_foods: @recipe } %>
	</div>
  </div>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>